version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
      # Replace the below TaskDefinition with your TaskDefinition
        TaskDefinition: "arn:aws:ecs:us-east-1:061350173834:task-definition/AppTaskDef"
        LoadBalancerInfo:
        #Replace the below ContainerName, ContainerPort with your ContainerName, ContainerPort
          ContainerName: "AppContainer"
          ContainerPort: 3010
