version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      # Replace the below REPOSITORY_URI with yours.
      - REPOSITORY_URI=061350173834.dkr.ecr.us-east-1.amazonaws.com/nodejslog/nodlogtest
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:latest nodeapps
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      #Replace the below container name with yours.
      - printf '[{"name":"osmoscontainer","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
    files: '**/*'
